// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajrzhrecwjxcohabagus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqcnpocmVjd2p4Y29oYWJhZ3VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDk2NTgsImV4cCI6MjA2NTU4NTY1OH0.ptv1yqk51ciyAH3LC-MNFeUUpdUXaoa5m-FtwZLDWJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);